{
    name: formula-bump,
    on:
        {
            schedule: [{ cron: "0 0 * * *" }],
            workflow_dispatch: {},
            push: { branches: [main] },
        },
    permissions: { contents: write, packages: write },
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}", BUILDRC: .buildrc },
    jobs:
        {
            main:
                {
                    runs-on: ubuntu-latest,
                    steps:
                        [
                            {
                                name: Check out code,
                                uses: actions/checkout@v3,
                                with: { clean: true, fetch-depth: 0 },
                            },
                            {
                                name: Set up Homebrew,
                                id: set-up-homebrew,
                                uses: Homebrew/actions/setup-homebrew@master,
                            },
                            {
                                name: Bump formulae,
                                uses: Homebrew/actions/bump-formulae@master,
                                with:
                                    {
                                        token: "${{ secrets.GITHUB_TOKEN }}",
                                        formulae: "tftab",
                                    },
                            },
                            {
                                name: Bump version and push tag,
                                id: tag_version,
                                uses: anothrNick/github-tag-action@1,
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                        WITH_V: false,
                                        DEFAULT_BUMP: patch,
                                        DRY_RUN: true,
                                    },
                            },
                            {
                                name: commit,
                                id: commit,
                                uses: stefanzweifel/git-auto-commit-action@v4,
                                env:
                                    {
                                        TAG: "${{ steps.tag_version.outputs.new_tag }}",
                                    },
                                with:
                                    {
                                        file_pattern: "Formula/*.rb",
                                        commit_message: "(formula-bump) ${{ env.TAG }}",
                                        commit_author: "github-actions <41898282+github-actions[bot]@users.noreply.github.com>",
                                    },
                            },
                            {
                                name: Create GitHub Release,
                                uses: ncipollo/release-action@v1,
                                if: "${{ steps.commit.outputs.changes_detected == 'true' }}",
                                env:
                                    {
                                        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
                                        TAG: "${{ steps.tag_version.outputs.new_tag }}",
                                    },
                                with:
                                    {
                                        tag: "${{ env.TAG }}",
                                        name: "${{ env.TAG }}",
                                        body: "Auto-generated release for ${{ env.TAG }}",
                                        draft: false,
                                        prerelease: false,
                                    },
                            },
                        ],
                },
        },
}
